코드 리펙토링
NaSol1One/MineSweeper pull request #2
Opened 2023-11-13 17:54 UTC by NaSol1One

지뢰찾기 게임보드 만들기 소스 코드 리팩토링

# 반영 브랜치
dev → master

#변경 사항
1. 변수명, 함수명(메소드명), 클래스명 변경
2. 큰 함수 → 작은 함수로 변경

2023-11-17 13:55 UTC, minsoowoo requested changes

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +public class Main {
클래스가 하나지만 클래스 이름도 변경해 주세요. 프로그램명이나 프로젝트명으로 변경하면 될 것 같아요.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
>              System.out.print("게임 보드의 크기 입력 (5~15) : ");
MinBoardSize와 MaxBoardSize가 변경될 때 게임 보드의 입력 범위도 같이 변경될 수 있도록 하드코딩보다 변수를 사용해서 출력주는게 좋겠네요.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
>          for (String[] strings : arr) Arrays.fill(strings, "O");
"O" 대신에 어떤 상태인지를 나타내는 변수로 변경하면 왜 "O"로 채우는지 이해하기가 더 쉬워질 것 같네요.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
>              arr[x][y] = "X";
여기도 "X" 대신에 이름을 붙여주는 게 좋아 보입니다.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +        String[][] arr = new String[size][size];
arr이 무엇을 위한 배열인지 의미가 있는 이름을 붙여 주는 게 좋겠네요.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +    public static void PrintBoard(String[][] arr) {
여기서 인자로 사용되는 arr는 PrintBoard 함수가 있어서 문맥상 이해는 되지만 조금 더 명확하게 하기 위해서 의미가 있는 이름으로 변경해 주는 것이 좀 더 좋아 보입니다.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +                if (!arr[i][j].equals("X")) CountMineOnBlank(arr, size, i, j);
"X"에 이름을 붙여주면 "X"랑 같다는 게 어떤 의미인지 더 이해하기가 쉬울 거에요. 55라인의 "X"와 같다면 클래스 멤버 변수로 정의하면 더욱 좋습니다.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +    public static String[][] CountMine(String[][] arr, int size) {
arr를 의미 있는 이름으로 변경합시다.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +        int[] dy = {-1, 0, 1, -1, 1, -1, 0, 1};
dx와 dy가 현재 칸의 주변 칸들을 나타내기 위한 정보를 가진 배열이라면 좀 더 좋은 이름으로 변경해야 이해가 될 것 같네요. xCoordinateOfSurroundingBlocks 같은 건 어떨까요?
-1, 0, 1은 현재 칸과의 상대적인 위치일텐데,  하드코딩된 숫자들을 전부 상수값을 가지는 final 변수로 변경하거나 주석으로 추가적인 정보를 제공하는 것이 좋겠네요.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +        for (int k = 0; k < 8; k++) {
숫자 8이 어떤 의미인지 이름을 가지는 변수로 변경해 줍시다.

2023-11-17 13:55 UTC, minsoowoo commented on src/Main.java
> +        boolean IsInRange = 0 <= next_x && next_x < size && 0 <= next_y && next_y < size;
=, <=, && 등이 여러 번 사용되어서 읽기가 힘드네요. 여러 줄로 변경하거나, 최소한 괄호()를 사용하여 우선순위라도 표시해 주는 것이 좋습니다. 예를 들어 ( 0 <= next_x ) && ( next_x < size) && 이런 식으로요.

2023-11-17 17:55 UTC, NaSol1One commented
@minsoowoo 

요청 주신 사항 수정했습니다.
수정된 코드 다시 한 번 확인해주세요.

1. Main > MineSweeper 로 이름 변경
2. 게임보드 입력 범위 출력 수정
3. Board의 O, X 변수로 정의
4. arr > gameBoard로 이름 변경
5. 주변 칸 확인하는 코드 수정
6. IsInRange에 괄호() 추가

2023-11-18 07:39 UTC, minsoowoo requested changes

2023-11-18 07:39 UTC, minsoowoo commented on src/MineSweeper.java
> +            size = ScanNum();
20-21 라인과 25-26 라인에서 동일한 코드가 반복되네요. 반복되는 코드를 함수로 만들어서 함수만 호출하는 방식으로 바꾸면 좋을 것 같아요

2023-11-18 07:39 UTC, minsoowoo commented on src/MineSweeper.java
> +            mine_num = ScanNum();
여기도 33-34 라인과 40-41 라인에서 반복되는 코드를 함수로 변경하면 좋겠네요.

2023-11-19 03:14 UTC, minsoowoo approved these changes
수정한 코드 확인했어요. 이정도면 충분하네요. 승인합니다.
수고했어요~ 👍

2023-11-19 03:14 UTC, merged